# Generated by Django 4.2.4 on 2024-12-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_projectjoinrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectjoinrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
    ]
