# Generated by Django 4.2.4 on 2024-10-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_projectfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
