# Generated by Django 4.2.4 on 2024-11-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_projectfiles_file'),
        ('users', '0006_projectfiles_audio_file_comment'),
    ]

    operations = [
    ]
