# Generated by Django 4.2.4 on 2024-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20241103_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='title',
            field=models.CharField(default='No-title', max_length=255),
            preserve_default=False,
        ),
    ]
