# Generated by Django 4.2.4 on 2024-11-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
