# Generated by Django 4.2.4 on 2024-11-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_comment_file_comment_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='comment',
            name='project_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.projectfiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
