# Generated by Django 4.2.4 on 2024-11-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_task_uploaded_by_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('waiting approval', 'Waiting Approval'), ('done', 'Done')], default='to do'),
        ),
    ]
