# Generated by Django 4.2.4 on 2024-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default='Default Value', max_length=30),
        ),
    ]
