# Generated by Django 4.2.4 on 2024-11-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_project_description_project_is_private'),
        ('users', '0013_merge_20241116_1140'),
    ]

    operations = [
    ]
