# Generated by Django 4.2.4 on 2024-11-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_comment_project_comment_file'),
        ('users', '0013_task_name'),
    ]

    operations = [
    ]
